; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG125006 DB	'D:\QT\5.12.2\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG125007 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125008 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG125367 DB	'D:\QT\5.12.2\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG125368 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125369 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG125728 DB	'D:\QT\5.12.2\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG125729 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125730 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Serialize@@3Uqt_meta_stringdata_Serialize_t@@B DD 0ffffffffH ; qt_meta_stringdata_Serialize
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	053H
	DB	065H
	DB	072H
	DB	069H
	DB	061H
	DB	06cH
	DB	069H
	DB	07aH
	DB	065H
	DB	00H
	ORG $+6
?qt_meta_data_Serialize@@3QBIB DD 08H			; qt_meta_data_Serialize
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Serialize@@UEBAPEBUQMetaObject@@XZ	; Serialize::metaObject
PUBLIC	?qt_metacast@Serialize@@UEAAPEAXPEBD@Z		; Serialize::qt_metacast
PUBLIC	?qt_metacall@Serialize@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Serialize::qt_metacall
PUBLIC	?qt_static_metacall@Serialize@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Serialize::qt_static_metacall
PUBLIC	?staticMetaObject@Serialize@@2UQMetaObject@@B	; Serialize::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QObject@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Serialize@@2UQMetaObject@@B DB 030H DUP (?) ; Serialize::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Serialize@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Serialize@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Serialize@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Serialize@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Serialize@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?qt_metacall@Serialize@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Serialize@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Serialize@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Serialize@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Serialize@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Serialize@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Serialize@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Serialize@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Serialize@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Serialize::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 66
	mov	rax, QWORD PTR __imp_?staticMetaObject@QObject@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Serialize@@2UQMetaObject@@B, rax
; Line 67
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Serialize@@3Uqt_meta_stringdata_Serialize_t@@B
	mov	QWORD PTR ?staticMetaObject@Serialize@@2UQMetaObject@@B+8, rax
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_data_Serialize@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Serialize@@2UQMetaObject@@B+16, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_static_metacall@Serialize@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Serialize::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Serialize@@2UQMetaObject@@B+24, rax
; Line 70
	mov	QWORD PTR ?staticMetaObject@Serialize@@2UQMetaObject@@B+32, 0
; Line 71
	mov	QWORD PTR ?staticMetaObject@Serialize@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Serialize@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Serialize::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@Serialize@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Serialize::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 58
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 63
	ret	0
?qt_static_metacall@Serialize@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Serialize::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Serialize@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Serialize::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 89
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 90
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 91
	mov	eax, DWORD PTR _id$[rsp]
; Line 92
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Serialize@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Serialize::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Serialize@@UEAAPEAXPEBD@Z PROC		; Serialize::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 81
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 82
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 83
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Serialize@@3Uqt_meta_stringdata_Serialize_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 84
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 85
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 86
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Serialize@@UEAAPEAXPEBD@Z ENDP		; Serialize::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Serialize@@UEBAPEBUQMetaObject@@XZ PROC	; Serialize::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 76
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 77
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Serialize@@2UQMetaObject@@B ; Serialize::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 78
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Serialize@@UEBAPEBUQMetaObject@@XZ ENDP	; Serialize::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.12.2\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 95
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Serialize.cpp
; Line 95
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
