; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG229644 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
$SG221675 DB	'x == d', 00H
	ORG $+5
$SG229645 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG229646 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG221645 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221646 DB	'asize >= 0 && asize <= aalloc', 00H
	ORG $+2
$SG221654 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221655 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG221656 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221657 DB	'!x->ref.isStatic()', 00H
	ORG $+5
$SG221670 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221671 DB	'int(d->alloc) == aalloc', 00H
$SG221672 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221673 DB	'isDetached()', 00H
	ORG $+3
$SG221674 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221683 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221684 DB	'd->data()', 00H
	ORG $+6
$SG221685 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221686 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+6
$SG221687 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221688 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG221689 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221690 DB	'aalloc ? d != Data::sharedNull() : d == Data::sharedNull'
	DB	'()', 00H
	ORG $+5
$SG221691 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221692 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+7
$SG221693 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qvector.h', 00H
	ORG $+6
$SG221694 DB	'd->size == asize', 00H
	ORG $+7
$SG230005 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG230006 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG230007 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG230513 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG230514 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG230515 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG222568 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG222569 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG222570 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG230874 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG230875 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG230876 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG222929 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG222930 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG222931 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG231235 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG231236 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG231237 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG223290 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG223291 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG223292 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG231596 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG231597 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG231598 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Server@@3Uqt_meta_stringdata_Server_t@@B DD 0ffffffffH ; qt_meta_stringdata_Server
	DD	06H
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000067H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000005dH
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000046H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000003bH
	DB	053H
	DB	065H
	DB	072H
	DB	076H
	DB	065H
	DB	072H
	DB	00H
	DB	06eH
	DB	065H
	DB	077H
	DB	043H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	00H
	DB	064H
	DB	069H
	DB	073H
	DB	063H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	079H
	DB	052H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	ORG $+3
	ORG $+8
?qt_meta_data_Server@@3QBIB DD 08H			; qt_meta_data_Server
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	01dH
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	01eH
	DD	02H
	DD	0aH
	DD	04H
	DD	00H
	DD	01fH
	DD	02H
	DD	0aH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG231988 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG231989 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG231990 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG224139 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG224140 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG224141 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG232349 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG232350 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG232351 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG232710 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG232711 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG232712 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG224539 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG224540 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG224541 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG233071 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG233072 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233073 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG224900 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG224901 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG224902 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG233432 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG233433 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233434 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG225261 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG225262 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG225263 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG233799 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG233800 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233801 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG225622 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG225623 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG225624 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234160 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG234161 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234162 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG217807 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG217808 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG217809 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG226008 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG226009 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG226010 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234559 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG234560 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234561 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG226369 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG226370 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG226371 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG226730 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG226731 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG226732 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234959 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG234960 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234961 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG227091 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG227092 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG227093 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG235359 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG235360 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG235361 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG235760 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG235761 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG235762 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG236121 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG236122 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG236123 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG228446 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG228447 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG228448 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG228846 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG228847 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG228848 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG229245 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG229246 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG229247 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Server@@UEBAPEBUQMetaObject@@XZ	; Server::metaObject
PUBLIC	?qt_metacast@Server@@UEAAPEAXPEBD@Z		; Server::qt_metacast
PUBLIC	?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_metacall
PUBLIC	?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_static_metacall
PUBLIC	?staticMetaObject@Server@@2UQMetaObject@@B	; Server::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?newConnection@Server@@QEAAXXZ:PROC		; Server::newConnection
EXTRN	?disconnected@Server@@QEAAXXZ:PROC		; Server::disconnected
EXTRN	?readyRead@Server@@QEAAXXZ:PROC			; Server::readyRead
EXTRN	__imp_?staticMetaObject@QObject@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Server@@2UQMetaObject@@B DB 030H DUP (?) ; Server::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Server@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Server@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Server@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Server@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+110
	DD	imagerel $unwind$?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Server@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Server@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Server@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Server@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Server::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 88
	mov	rax, QWORD PTR __imp_?staticMetaObject@QObject@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B, rax
; Line 89
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Server@@3Uqt_meta_stringdata_Server_t@@B
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+8, rax
; Line 90
	lea	rax, OFFSET FLAT:?qt_meta_data_Server@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+16, rax
; Line 91
	lea	rax, OFFSET FLAT:?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+24, rax
; Line 92
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+32, 0
; Line 93
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Server::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Server::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 73
$LN10:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 74
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 75
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 77
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN8@qt_static_
$LN5@qt_static_:
; Line 78
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?newConnection@Server@@QEAAXXZ		; Server::newConnection
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 79
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?disconnected@Server@@QEAAXXZ		; Server::disconnected
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 80
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?readyRead@Server@@QEAAXXZ		; Server::readyRead
$LN8@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 85
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Server::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Server::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 111
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 112
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 113
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 114
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 115
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 116
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 117
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_static_metacall
$LN5@qt_metacal:
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 119
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 120
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 121
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 124
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 125
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Server::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Server@@UEAAPEAXPEBD@Z PROC		; Server::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 103
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 104
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 105
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Server@@3Uqt_meta_stringdata_Server_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 106
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 107
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 108
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Server@@UEAAPEAXPEBD@Z ENDP		; Server::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Server@@UEBAPEBUQMetaObject@@XZ PROC	; Server::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 98
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 99
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Server@@2UQMetaObject@@B ; Server::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 100
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Server@@UEBAPEBUQMetaObject@@XZ ENDP	; Server::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.12.3\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 128
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 128
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
