; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG245868 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG245869 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG245870 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG237855 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+3
$SG231494 DB	'd != x', 00H
	ORG $+5
$SG237857 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+12
$SG237856 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG246312 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG246313 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG246314 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG238216 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG238217 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG238218 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG246756 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG246757 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG246758 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG247163 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG247164 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247165 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG247524 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG247525 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247526 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG239557 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG239558 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG239559 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG231478 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231479 DB	'aalloc >= d->size', 00H
	ORG $+6
$SG231482 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+9
$SG231483 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG231484 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231485 DB	'!x->ref.isStatic()', 00H
	ORG $+5
$SG231493 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231499 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231500 DB	'd->data()', 00H
	ORG $+6
$SG247885 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG231501 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+9
$SG247886 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG231502 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+6
$SG247887 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG231503 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231504 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG231505 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231506 DB	'd != Data::sharedNull()', 00H
$SG231507 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qvector.h', 00H
	ORG $+1
$SG231508 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+7
$SG240001 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG240002 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG240003 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG256679 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG256680 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG256681 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG240444 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG240445 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG240446 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG232521 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG232522 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG232523 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG240887 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG240888 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG240889 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG232868 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG232869 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG232870 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Server@@3Uqt_meta_stringdata_Server_t@@B DD 0ffffffffH ; qt_meta_stringdata_Server
	DD	06H
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000067H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000005dH
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000046H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000003bH
	DB	053H
	DB	065H
	DB	072H
	DB	076H
	DB	065H
	DB	072H
	DB	00H
	DB	06eH
	DB	065H
	DB	077H
	DB	043H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	00H
	DB	064H
	DB	069H
	DB	073H
	DB	063H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	079H
	DB	052H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	ORG $+3
	ORG $+8
?qt_meta_data_Server@@3QBIB DD 08H			; qt_meta_data_Server
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	01dH
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	01eH
	DD	02H
	DD	0aH
	DD	04H
	DD	00H
	DD	01fH
	DD	02H
	DD	0aH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG241248 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG241250 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+12
$SG241249 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233229 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG233230 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233231 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG241776 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG241777 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG241778 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG242139 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG242140 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG242141 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG242500 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG242501 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG242502 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234312 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG234313 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234314 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG242861 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG242862 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG242863 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234760 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG234761 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234762 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG243253 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG243254 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG243255 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG235121 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG235122 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG235123 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG243614 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG243615 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG243616 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG235482 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG235483 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG235484 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG243975 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG243976 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG243977 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG235843 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG235844 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG235845 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG244336 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG244337 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG244338 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG236243 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG236244 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG236245 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG228211 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG228212 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG228213 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG244697 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG244698 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG244699 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG236604 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG236605 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG236606 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG245064 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG245065 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG245066 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG236965 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG236966 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG236967 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG245425 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG245426 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG245427 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG237411 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG237412 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG237413 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Server@@UEBAPEBUQMetaObject@@XZ	; Server::metaObject
PUBLIC	?qt_metacast@Server@@UEAAPEAXPEBD@Z		; Server::qt_metacast
PUBLIC	?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_metacall
PUBLIC	?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QObject::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>
PUBLIC	?staticMetaObject@Server@@2UQMetaObject@@B	; Server::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?newConnection@Server@@QEAAXXZ:PROC		; Server::newConnection
EXTRN	?disconnected@Server@@QEAAXXZ:PROC		; Server::disconnected
EXTRN	?readyRead@Server@@QEAAXXZ:PROC			; Server::readyRead
EXTRN	__imp_?staticMetaObject@QObject@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Server@@2UQMetaObject@@B DB 030H DUP (?) ; Server::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Server@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Server@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Server@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Server@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+110
	DD	imagerel $unwind$?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Server@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Server@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@Server@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Server@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Server::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 95
	sub	rsp, 40					; 00000028H
; Line 89
	lea	rcx, OFFSET FLAT:?staticMetaObject@Server@@2UQMetaObject@@B ; Server::staticMetaObject
	call	??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QObject::staticMetaObject>
; Line 90
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Server@@3Uqt_meta_stringdata_Server_t@@B
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+8, rax
; Line 91
	lea	rax, OFFSET FLAT:?qt_meta_data_Server@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+16, rax
; Line 92
	lea	rax, OFFSET FLAT:?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+24, rax
; Line 93
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+32, 0
; Line 94
	mov	QWORD PTR ?staticMetaObject@Server@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@Server@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Server::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QObject@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QObject::staticMetaObject>, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QObject::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Server::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 74
$LN10:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 75
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 76
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 78
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN8@qt_static_
$LN5@qt_static_:
; Line 79
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?newConnection@Server@@QEAAXXZ		; Server::newConnection
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 80
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?disconnected@Server@@QEAAXXZ		; Server::disconnected
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 81
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?readyRead@Server@@QEAAXXZ		; Server::readyRead
$LN8@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 86
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Server::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Server::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 112
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 113
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 114
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 115
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 116
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 117
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 118
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@Server@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Server::qt_static_metacall
$LN5@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 120
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 121
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 122
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 126
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Server@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Server::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Server@@UEAAPEAXPEBD@Z PROC		; Server::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 104
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 105
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 106
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Server@@3Uqt_meta_stringdata_Server_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 107
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 108
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 109
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Server@@UEAAPEAXPEBD@Z ENDP		; Server::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Server@@UEBAPEBUQMetaObject@@XZ PROC	; Server::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 99
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 100
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Server@@2UQMetaObject@@B ; Server::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 101
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Server@@UEBAPEBUQMetaObject@@XZ ENDP	; Server::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 129
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Server\Server\GeneratedFiles\Debug\moc_Server.cpp
; Line 129
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
