; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG139523 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG139524 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139525 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG140373 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG140374 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG140375 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_RegisterWindow@@3Uqt_meta_stringdata_RegisterWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_RegisterWindow
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000057H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000055H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	000000000000003eH
	DB	052H
	DB	065H
	DB	067H
	DB	069H
	DB	073H
	DB	074H
	DB	065H
	DB	072H
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	070H
	DB	075H
	DB	073H
	DB	068H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06cH
	DB	06fH
	DB	067H
	DB	069H
	DB	06eH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+3
?qt_meta_data_RegisterWindow@@3QBIB DD 08H		; qt_meta_data_RegisterWindow
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	019H
	DD	02H
	DD	0aH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG135756 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG135757 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG135758 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG138801 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG138802 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138803 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG139162 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG139163 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139164 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@RegisterWindow@@UEBAPEBUQMetaObject@@XZ ; RegisterWindow::metaObject
PUBLIC	?qt_metacast@RegisterWindow@@UEAAPEAXPEBD@Z	; RegisterWindow::qt_metacast
PUBLIC	?qt_metacall@RegisterWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; RegisterWindow::qt_metacall
PUBLIC	?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; RegisterWindow::qt_static_metacall
PUBLIC	?staticMetaObject@RegisterWindow@@2UQMetaObject@@B ; RegisterWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?on_pushButton_clicked@RegisterWindow@@QEAAXXZ:PROC ; RegisterWindow::on_pushButton_clicked
EXTRN	?on_loginButton_clicked@RegisterWindow@@QEAAXXZ:PROC ; RegisterWindow::on_loginButton_clicked
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@RegisterWindow@@2UQMetaObject@@B DB 030H DUP (?) ; RegisterWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@RegisterWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@RegisterWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@RegisterWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@RegisterWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@RegisterWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@RegisterWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+91
	DD	imagerel $unwind$?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@RegisterWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@RegisterWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@RegisterWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@RegisterWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@RegisterWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@RegisterWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@RegisterWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@RegisterWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'RegisterWindow::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 84
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@RegisterWindow@@2UQMetaObject@@B, rax
; Line 85
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_RegisterWindow@@3Uqt_meta_stringdata_RegisterWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@RegisterWindow@@2UQMetaObject@@B+8, rax
; Line 86
	lea	rax, OFFSET FLAT:?qt_meta_data_RegisterWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@RegisterWindow@@2UQMetaObject@@B+16, rax
; Line 87
	lea	rax, OFFSET FLAT:?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; RegisterWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@RegisterWindow@@2UQMetaObject@@B+24, rax
; Line 88
	mov	QWORD PTR ?staticMetaObject@RegisterWindow@@2UQMetaObject@@B+32, 0
; Line 89
	mov	QWORD PTR ?staticMetaObject@RegisterWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@RegisterWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'RegisterWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; RegisterWindow::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 70
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 71
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 72
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 74
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN5@qt_static_:
; Line 75
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_pushButton_clicked@RegisterWindow@@QEAAXXZ ; RegisterWindow::on_pushButton_clicked
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 76
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_loginButton_clicked@RegisterWindow@@QEAAXXZ ; RegisterWindow::on_loginButton_clicked
$LN7@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 81
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; RegisterWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@RegisterWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; RegisterWindow::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 107
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 108
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 109
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 110
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 111
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 112
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 113
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@RegisterWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; RegisterWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 114
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 115
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 116
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 117
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 120
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 121
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@RegisterWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; RegisterWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@RegisterWindow@@UEAAPEAXPEBD@Z PROC	; RegisterWindow::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 99
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 100
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 101
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_RegisterWindow@@3Uqt_meta_stringdata_RegisterWindow_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 102
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 103
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 104
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@RegisterWindow@@UEAAPEAXPEBD@Z ENDP	; RegisterWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@RegisterWindow@@UEBAPEBUQMetaObject@@XZ PROC ; RegisterWindow::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 94
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 95
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@RegisterWindow@@2UQMetaObject@@B ; RegisterWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 96
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@RegisterWindow@@UEBAPEBUQMetaObject@@XZ ENDP ; RegisterWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.12.3\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 124
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_RegisterWindow.cpp
; Line 124
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
