; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG156897 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG156898 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG156899 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG157244 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG157245 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157246 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG157605 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG157606 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157607 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_FileExplorerWindow@@3Uqt_meta_stringdata_FileExplorerWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_FileExplorerWindow
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000090H
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	000000000000008bH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000008cH
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	0000000000000075H
	DD	0ffffffffH
	DD	01cH
	DD	00H
	ORG $+4
	DQ	0000000000000077H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	000000000000007cH
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	045H
	DB	078H
	DB	070H
	DB	06cH
	DB	06fH
	DB	072H
	DB	065H
	DB	072H
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06eH
	DB	065H
	DB	077H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06cH
	DB	06fH
	DB	061H
	DB	064H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06cH
	DB	06fH
	DB	061H
	DB	064H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	055H
	DB	052H
	DB	049H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	074H
	DB	06fH
	DB	06fH
	DB	06cH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+6
?qt_meta_data_FileExplorerWindow@@3QBIB DD 08H		; qt_meta_data_FileExplorerWindow
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	022H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	023H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	024H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	025H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG158688 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG158689 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG158690 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG159049 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG159050 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG159051 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG159410 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG159411 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG159412 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG159854 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG159855 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG159856 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG153744 DB	'D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qmetatype.h'
	DB	00H
	ORG $+7
$SG153745 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG153746 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@FileExplorerWindow@@UEBAPEBUQMetaObject@@XZ ; FileExplorerWindow::metaObject
PUBLIC	?qt_metacast@FileExplorerWindow@@UEAAPEAXPEBD@Z	; FileExplorerWindow::qt_metacast
PUBLIC	?qt_metacall@FileExplorerWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; FileExplorerWindow::qt_metacall
PUBLIC	?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; FileExplorerWindow::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
PUBLIC	?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B ; FileExplorerWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?on_newFileButton_clicked@FileExplorerWindow@@AEAAXXZ:PROC ; FileExplorerWindow::on_newFileButton_clicked
EXTRN	?on_loadFileButton_clicked@FileExplorerWindow@@AEAAXXZ:PROC ; FileExplorerWindow::on_loadFileButton_clicked
EXTRN	?on_loadFileURIButton_clicked@FileExplorerWindow@@AEAAXXZ:PROC ; FileExplorerWindow::on_loadFileURIButton_clicked
EXTRN	?on_toolButton_clicked@FileExplorerWindow@@AEAAXXZ:PROC ; FileExplorerWindow::on_toolButton_clicked
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B DB 030H DUP (?) ; FileExplorerWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@FileExplorerWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@FileExplorerWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@FileExplorerWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@FileExplorerWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@FileExplorerWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@FileExplorerWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN11
	DD	imagerel $LN11+129
	DD	imagerel $unwind$?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@FileExplorerWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@FileExplorerWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@FileExplorerWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@FileExplorerWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@FileExplorerWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'FileExplorerWindow::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 101
	sub	rsp, 40					; 00000028H
; Line 95
	lea	rcx, OFFSET FLAT:?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B ; FileExplorerWindow::staticMetaObject
	call	??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
; Line 96
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_FileExplorerWindow@@3Uqt_meta_stringdata_FileExplorerWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B+8, rax
; Line 97
	lea	rax, OFFSET FLAT:?qt_meta_data_FileExplorerWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B+16, rax
; Line 98
	lea	rax, OFFSET FLAT:?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; FileExplorerWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B+24, rax
; Line 99
	mov	QWORD PTR ?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B+32, 0
; Line 100
	mov	QWORD PTR ?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'FileExplorerWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; FileExplorerWindow::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 79
$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 80
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 81
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 83
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN8@qt_static_
	jmp	SHORT $LN9@qt_static_
$LN5@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_newFileButton_clicked@FileExplorerWindow@@AEAAXXZ ; FileExplorerWindow::on_newFileButton_clicked
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 85
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_loadFileButton_clicked@FileExplorerWindow@@AEAAXXZ ; FileExplorerWindow::on_loadFileButton_clicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 86
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_loadFileURIButton_clicked@FileExplorerWindow@@AEAAXXZ ; FileExplorerWindow::on_loadFileURIButton_clicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 87
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_toolButton_clicked@FileExplorerWindow@@AEAAXXZ ; FileExplorerWindow::on_toolButton_clicked
$LN9@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 92
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; FileExplorerWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@FileExplorerWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; FileExplorerWindow::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 118
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 119
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 120
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 121
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 122
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 123
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN5@qt_metacal
; Line 124
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@FileExplorerWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; FileExplorerWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 126
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 127
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN7@qt_metacal
; Line 128
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 129
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 131
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 132
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@FileExplorerWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; FileExplorerWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@FileExplorerWindow@@UEAAPEAXPEBD@Z PROC	; FileExplorerWindow::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 110
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 111
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 112
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_FileExplorerWindow@@3Uqt_meta_stringdata_FileExplorerWindow_t@@B+144
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 113
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 114
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 115
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@FileExplorerWindow@@UEAAPEAXPEBD@Z ENDP	; FileExplorerWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@FileExplorerWindow@@UEBAPEBUQMetaObject@@XZ PROC ; FileExplorerWindow::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 105
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 106
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@FileExplorerWindow@@2UQMetaObject@@B ; FileExplorerWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 107
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@FileExplorerWindow@@UEBAPEBUQMetaObject@@XZ ENDP ; FileExplorerWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File D:\QT\5.15\5.15.1\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 135
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_FileExplorerWindow.cpp
; Line 135
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
