; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG131348 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG131349 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG131350 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG134370 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG134371 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG134372 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG134731 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG134732 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG134733 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG135092 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG135093 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG135094 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG135942 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG135943 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG135944 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_TextEdit@@3Uqt_meta_stringdata_TextEdit_t@@B DD 0ffffffffH ; qt_meta_stringdata_TextEdit
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000378H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000369H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000359H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000342H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000339H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	000000000000032aH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	000000000000031bH
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000030eH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000300H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	00000000000002f9H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	00000000000002eeH
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	00000000000002dfH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000002d5H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000002c8H
	DD	0ffffffffH
	DD	01H
	DD	00H
	ORG $+4
	DQ	00000000000002bbH
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	00000000000002a5H
	DD	0ffffffffH
	DD	01H
	DD	00H
	ORG $+4
	DQ	0000000000000296H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000280H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000272H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000265H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000257H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000250H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000246H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000234H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000226H
	DD	0ffffffffH
	DD	01H
	DD	00H
	ORG $+4
	DQ	0000000000000217H
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	0000000000000201H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	0000000000000202H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	00000000000001faH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	00000000000001e9H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000001e7H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000001e4H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	00000000000001d2H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	00000000000001c7H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000001b9H
	DD	0ffffffffH
	DD	02H
	DD	00H
	ORG $+4
	DQ	00000000000001b2H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	000000000000019dH
	DB	054H
	DB	065H
	DB	078H
	DB	074H
	DB	045H
	DB	064H
	DB	069H
	DB	074H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	04eH
	DB	065H
	DB	077H
	DB	00H
	DB	00H
	DB	073H
	DB	065H
	DB	074H
	DB	053H
	DB	061H
	DB	076H
	DB	069H
	DB	06eH
	DB	067H
	DB	054H
	DB	069H
	DB	06dH
	DB	065H
	DB	072H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	04fH
	DB	070H
	DB	065H
	DB	06eH
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	053H
	DB	061H
	DB	076H
	DB	065H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	053H
	DB	061H
	DB	076H
	DB	065H
	DB	041H
	DB	073H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	050H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	050H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	050H
	DB	072H
	DB	065H
	DB	076H
	DB	069H
	DB	065H
	DB	077H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	050H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	050H
	DB	064H
	DB	066H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	042H
	DB	06fH
	DB	06cH
	DB	064H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	055H
	DB	06eH
	DB	064H
	DB	065H
	DB	072H
	DB	06cH
	DB	069H
	DB	06eH
	DB	065H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	049H
	DB	074H
	DB	061H
	DB	06cH
	DB	069H
	DB	063H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	046H
	DB	061H
	DB	06dH
	DB	069H
	DB	06cH
	DB	079H
	DB	00H
	DB	066H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	053H
	DB	069H
	DB	07aH
	DB	065H
	DB	00H
	DB	070H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	053H
	DB	074H
	DB	079H
	DB	06cH
	DB	065H
	DB	00H
	DB	073H
	DB	074H
	DB	079H
	DB	06cH
	DB	065H
	DB	049H
	DB	06eH
	DB	064H
	DB	065H
	DB	078H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	043H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	00H
	DB	067H
	DB	065H
	DB	074H
	DB	041H
	DB	06cH
	DB	069H
	DB	067H
	DB	06eH
	DB	06dH
	DB	065H
	DB	06eH
	DB	074H
	DB	043H
	DB	06fH
	DB	064H
	DB	065H
	DB	00H
	DB	051H
	DB	074H
	DB	03aH
	DB	03aH
	DB	041H
	DB	06cH
	DB	069H
	DB	067H
	DB	06eH
	DB	06dH
	DB	065H
	DB	06eH
	DB	074H
	DB	00H
	DB	061H
	DB	06cH
	DB	069H
	DB	067H
	DB	06eH
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	041H
	DB	06cH
	DB	069H
	DB	067H
	DB	06eH
	DB	00H
	DB	051H
	DB	041H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	02aH
	DB	00H
	DB	061H
	DB	00H
	DB	063H
	DB	075H
	DB	072H
	DB	072H
	DB	065H
	DB	06eH
	DB	074H
	DB	043H
	DB	068H
	DB	061H
	DB	072H
	DB	046H
	DB	06fH
	DB	072H
	DB	06dH
	DB	061H
	DB	074H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	051H
	DB	054H
	DB	065H
	DB	078H
	DB	074H
	DB	043H
	DB	068H
	DB	061H
	DB	072H
	DB	046H
	DB	06fH
	DB	072H
	DB	06dH
	DB	061H
	DB	074H
	DB	00H
	DB	066H
	DB	06fH
	DB	072H
	DB	06dH
	DB	061H
	DB	074H
	DB	00H
	DB	063H
	DB	075H
	DB	072H
	DB	073H
	DB	06fH
	DB	072H
	DB	050H
	DB	06fH
	DB	073H
	DB	069H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	063H
	DB	06cH
	DB	069H
	DB	070H
	DB	062H
	DB	06fH
	DB	061H
	DB	072H
	DB	064H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	061H
	DB	062H
	DB	06fH
	DB	075H
	DB	074H
	DB	00H
	DB	070H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	050H
	DB	072H
	DB	065H
	DB	076H
	DB	069H
	DB	065H
	DB	077H
	DB	00H
	DB	051H
	DB	050H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	065H
	DB	072H
	DB	02aH
	DB	00H
	DB	061H
	DB	064H
	DB	064H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	054H
	DB	06fH
	DB	054H
	DB	06fH
	DB	06fH
	DB	06cH
	DB	062H
	DB	061H
	DB	072H
	DB	00H
	DB	069H
	DB	064H
	DB	00H
	DB	061H
	DB	064H
	DB	064H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	054H
	DB	06fH
	DB	054H
	DB	06fH
	DB	06fH
	DB	06cH
	DB	062H
	DB	061H
	DB	072H
	DB	057H
	DB	072H
	DB	069H
	DB	074H
	DB	069H
	DB	06eH
	DB	067H
	DB	00H
	ORG $+3
	ORG $+8
?qt_meta_data_TextEdit@@3QBIB DD 08H			; qt_meta_data_TextEdit
	DD	00H
	DD	00H
	DD	00H
	DD	018H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	086H
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	087H
	DD	02H
	DD	0aH
	DD	04H
	DD	00H
	DD	088H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	089H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	08aH
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	08bH
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	08cH
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	08dH
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	08eH
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	08fH
	DD	02H
	DD	08H
	DD	0cH
	DD	00H
	DD	090H
	DD	02H
	DD	08H
	DD	0dH
	DD	01H
	DD	091H
	DD	02H
	DD	08H
	DD	0fH
	DD	01H
	DD	094H
	DD	02H
	DD	08H
	DD	011H
	DD	01H
	DD	097H
	DD	02H
	DD	08H
	DD	013H
	DD	00H
	DD	09aH
	DD	02H
	DD	08H
	DD	014H
	DD	01H
	DD	09bH
	DD	02H
	DD	08H
	DD	017H
	DD	01H
	DD	09eH
	DD	02H
	DD	08H
	DD	01aH
	DD	01H
	DD	0a1H
	DD	02H
	DD	08H
	DD	01dH
	DD	00H
	DD	0a4H
	DD	02H
	DD	08H
	DD	01eH
	DD	00H
	DD	0a5H
	DD	02H
	DD	08H
	DD	01fH
	DD	00H
	DD	0a6H
	DD	02H
	DD	08H
	DD	020H
	DD	01H
	DD	0a7H
	DD	02H
	DD	08H
	DD	022H
	DD	01H
	DD	0aaH
	DD	02H
	DD	08H
	DD	024H
	DD	01H
	DD	0adH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	01H
	DD	01H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	0aH
	DD	0eH
	DD	02bH
	DD	0aH
	DD	010H
	DD	02bH
	DD	02H
	DD	012H
	DD	02bH
	DD	02H
	DD	080000015H
	DD	016H
	DD	02bH
	DD	080000018H
	DD	019H
	DD	02bH
	DD	08000001bH
	DD	01cH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	080000021H
	DD	02H
	DD	02bH
	DD	02H
	DD	023H
	DD	02bH
	DD	02H
	DD	023H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@TextEdit@@UEBAPEBUQMetaObject@@XZ	; TextEdit::metaObject
PUBLIC	?qt_metacast@TextEdit@@UEAAPEAXPEBD@Z		; TextEdit::qt_metacast
PUBLIC	?qt_metacall@TextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; TextEdit::qt_metacall
PUBLIC	?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TextEdit::qt_static_metacall
PUBLIC	??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z		; std::move<bool &>
PUBLIC	??$move@AEAH@std@@YA$$QEAHAEAH@Z		; std::move<int &>
PUBLIC	?staticMetaObject@TextEdit@@2UQMetaObject@@B	; TextEdit::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?fileNew@TextEdit@@QEAAXXZ:PROC			; TextEdit::fileNew
EXTRN	?setSavingTimer@TextEdit@@QEAAXXZ:PROC		; TextEdit::setSavingTimer
EXTRN	?fileOpen@TextEdit@@AEAAXXZ:PROC		; TextEdit::fileOpen
EXTRN	?fileSave@TextEdit@@AEAA_NXZ:PROC		; TextEdit::fileSave
EXTRN	?fileSaveAs@TextEdit@@AEAA_NXZ:PROC		; TextEdit::fileSaveAs
EXTRN	?filePrint@TextEdit@@AEAAXXZ:PROC		; TextEdit::filePrint
EXTRN	?filePrintPreview@TextEdit@@AEAAXXZ:PROC	; TextEdit::filePrintPreview
EXTRN	?filePrintPdf@TextEdit@@AEAAXXZ:PROC		; TextEdit::filePrintPdf
EXTRN	?textBold@TextEdit@@AEAAXXZ:PROC		; TextEdit::textBold
EXTRN	?textUnderline@TextEdit@@AEAAXXZ:PROC		; TextEdit::textUnderline
EXTRN	?textItalic@TextEdit@@AEAAXXZ:PROC		; TextEdit::textItalic
EXTRN	?textFamily@TextEdit@@AEAAXAEBVQString@@@Z:PROC	; TextEdit::textFamily
EXTRN	?textSize@TextEdit@@AEAAXAEBVQString@@@Z:PROC	; TextEdit::textSize
EXTRN	?textStyle@TextEdit@@AEAAXH@Z:PROC		; TextEdit::textStyle
EXTRN	?textColor@TextEdit@@AEAAXXZ:PROC		; TextEdit::textColor
EXTRN	?getAlignmentCode@TextEdit@@AEAAHV?$QFlags@W4AlignmentFlag@Qt@@@@@Z:PROC ; TextEdit::getAlignmentCode
EXTRN	?textAlign@TextEdit@@AEAAXPEAVQAction@@@Z:PROC	; TextEdit::textAlign
EXTRN	?currentCharFormatChanged@TextEdit@@AEAAXAEBVQTextCharFormat@@@Z:PROC ; TextEdit::currentCharFormatChanged
EXTRN	?cursorPositionChanged@TextEdit@@AEAAXXZ:PROC	; TextEdit::cursorPositionChanged
EXTRN	?clipboardDataChanged@TextEdit@@AEAAXXZ:PROC	; TextEdit::clipboardDataChanged
EXTRN	?about@TextEdit@@AEAAXXZ:PROC			; TextEdit::about
EXTRN	?printPreview@TextEdit@@AEAAXPEAVQPrinter@@@Z:PROC ; TextEdit::printPreview
EXTRN	?addUserToToolbar@TextEdit@@AEAAXH@Z:PROC	; TextEdit::addUserToToolbar
EXTRN	?addUserToToolbarWriting@TextEdit@@AEAAXH@Z:PROC ; TextEdit::addUserToToolbarWriting
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@TextEdit@@2UQMetaObject@@B DB 030H DUP (?) ; TextEdit::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@TextEdit@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@TextEdit@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@TextEdit@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@TextEdit@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@TextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@TextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN35
	DD	imagerel $LN35+880
	DD	imagerel $unwind$?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@TextEdit@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@TextEdit@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@TextEdit@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@TextEdit@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@TextEdit@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@TextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	08217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@TextEdit@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@TextEdit@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'TextEdit::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 195
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@TextEdit@@2UQMetaObject@@B, rax
; Line 196
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_TextEdit@@3Uqt_meta_stringdata_TextEdit_t@@B
	mov	QWORD PTR ?staticMetaObject@TextEdit@@2UQMetaObject@@B+8, rax
; Line 197
	lea	rax, OFFSET FLAT:?qt_meta_data_TextEdit@@3QBIB
	mov	QWORD PTR ?staticMetaObject@TextEdit@@2UQMetaObject@@B+16, rax
; Line 198
	lea	rax, OFFSET FLAT:?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TextEdit::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@TextEdit@@2UQMetaObject@@B+24, rax
; Line 199
	mov	QWORD PTR ?staticMetaObject@TextEdit@@2UQMetaObject@@B+32, 0
; Line 200
	mov	QWORD PTR ?staticMetaObject@TextEdit@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@TextEdit@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'TextEdit::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$move@AEAH@std@@YA$$QEAHAEAH@Z
_TEXT	SEGMENT
_Arg$ = 8
??$move@AEAH@std@@YA$$QEAHAEAH@Z PROC			; std::move<int &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\type_traits
; Line 1313
	mov	QWORD PTR [rsp+8], rcx
; Line 1314
	mov	rax, QWORD PTR _Arg$[rsp]
; Line 1315
	ret	0
??$move@AEAH@std@@YA$$QEAHAEAH@Z ENDP			; std::move<int &>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z
_TEXT	SEGMENT
_Arg$ = 8
??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z PROC		; std::move<bool &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\type_traits
; Line 1313
	mov	QWORD PTR [rsp+8], rcx
; Line 1314
	mov	rax, QWORD PTR _Arg$[rsp]
; Line 1315
	ret	0
??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z ENDP		; std::move<bool &>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_r$1 = 32
_r$2 = 33
tv69 = 36
_r$3 = 40
_t$4 = 48
_o$ = 80
_c$ = 88
_id$ = 96
_a$ = 104
?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; TextEdit::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 157
$LN35:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 158
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 159
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$4[rsp], rax
; Line 161
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 23
	ja	$LN32@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN34@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 162
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?fileNew@TextEdit@@QEAAXXZ		; TextEdit::fileNew
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 163
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?setSavingTimer@TextEdit@@QEAAXXZ	; TextEdit::setSavingTimer
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 164
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?fileOpen@TextEdit@@AEAAXXZ		; TextEdit::fileOpen
	jmp	$LN2@qt_static_
$LN8@qt_static_:
; Line 165
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?fileSave@TextEdit@@AEAA_NXZ		; TextEdit::fileSave
	mov	BYTE PTR _r$1[rsp], al
; Line 166
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN9@qt_static_
	lea	rcx, QWORD PTR _r$1[rsp]
	call	??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z	; std::move<bool &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR [rcx], al
$LN9@qt_static_:
	jmp	$LN2@qt_static_
$LN10@qt_static_:
; Line 167
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?fileSaveAs@TextEdit@@AEAA_NXZ		; TextEdit::fileSaveAs
	mov	BYTE PTR _r$2[rsp], al
; Line 168
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN11@qt_static_
	lea	rcx, QWORD PTR _r$2[rsp]
	call	??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z	; std::move<bool &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR [rcx], al
$LN11@qt_static_:
	jmp	$LN2@qt_static_
$LN12@qt_static_:
; Line 169
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?filePrint@TextEdit@@AEAAXXZ		; TextEdit::filePrint
	jmp	$LN2@qt_static_
$LN13@qt_static_:
; Line 170
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?filePrintPreview@TextEdit@@AEAAXXZ	; TextEdit::filePrintPreview
	jmp	$LN2@qt_static_
$LN14@qt_static_:
; Line 171
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?filePrintPdf@TextEdit@@AEAAXXZ		; TextEdit::filePrintPdf
	jmp	$LN2@qt_static_
$LN15@qt_static_:
; Line 172
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textBold@TextEdit@@AEAAXXZ		; TextEdit::textBold
	jmp	$LN2@qt_static_
$LN16@qt_static_:
; Line 173
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textUnderline@TextEdit@@AEAAXXZ	; TextEdit::textUnderline
	jmp	$LN2@qt_static_
$LN17@qt_static_:
; Line 174
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textItalic@TextEdit@@AEAAXXZ		; TextEdit::textItalic
	jmp	$LN2@qt_static_
$LN18@qt_static_:
; Line 175
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textFamily@TextEdit@@AEAAXAEBVQString@@@Z ; TextEdit::textFamily
	jmp	$LN2@qt_static_
$LN19@qt_static_:
; Line 176
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textSize@TextEdit@@AEAAXAEBVQString@@@Z ; TextEdit::textSize
	jmp	$LN2@qt_static_
$LN20@qt_static_:
; Line 177
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textStyle@TextEdit@@AEAAXH@Z		; TextEdit::textStyle
	jmp	$LN2@qt_static_
$LN21@qt_static_:
; Line 178
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textColor@TextEdit@@AEAAXXZ		; TextEdit::textColor
	jmp	$LN2@qt_static_
$LN22@qt_static_:
; Line 179
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?getAlignmentCode@TextEdit@@AEAAHV?$QFlags@W4AlignmentFlag@Qt@@@@@Z ; TextEdit::getAlignmentCode
	mov	DWORD PTR _r$3[rsp], eax
; Line 180
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN23@qt_static_
	lea	rcx, QWORD PTR _r$3[rsp]
	call	??$move@AEAH@std@@YA$$QEAHAEAH@Z	; std::move<int &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR [rcx], eax
$LN23@qt_static_:
	jmp	$LN2@qt_static_
$LN24@qt_static_:
; Line 181
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?textAlign@TextEdit@@AEAAXPEAVQAction@@@Z ; TextEdit::textAlign
	jmp	$LN2@qt_static_
$LN25@qt_static_:
; Line 182
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?currentCharFormatChanged@TextEdit@@AEAAXAEBVQTextCharFormat@@@Z ; TextEdit::currentCharFormatChanged
	jmp	$LN2@qt_static_
$LN26@qt_static_:
; Line 183
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?cursorPositionChanged@TextEdit@@AEAAXXZ ; TextEdit::cursorPositionChanged
	jmp	SHORT $LN2@qt_static_
$LN27@qt_static_:
; Line 184
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?clipboardDataChanged@TextEdit@@AEAAXXZ	; TextEdit::clipboardDataChanged
	jmp	SHORT $LN2@qt_static_
$LN28@qt_static_:
; Line 185
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?about@TextEdit@@AEAAXXZ		; TextEdit::about
	jmp	SHORT $LN2@qt_static_
$LN29@qt_static_:
; Line 186
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?printPreview@TextEdit@@AEAAXPEAVQPrinter@@@Z ; TextEdit::printPreview
	jmp	SHORT $LN2@qt_static_
$LN30@qt_static_:
; Line 187
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?addUserToToolbar@TextEdit@@AEAAXH@Z	; TextEdit::addUserToToolbar
	jmp	SHORT $LN2@qt_static_
$LN31@qt_static_:
; Line 188
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?addUserToToolbarWriting@TextEdit@@AEAAXH@Z ; TextEdit::addUserToToolbarWriting
$LN32@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 192
	add	rsp, 72					; 00000048H
	ret	0
	npad	3
$LN34@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN10@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
	DD	$LN18@qt_static_
	DD	$LN19@qt_static_
	DD	$LN20@qt_static_
	DD	$LN21@qt_static_
	DD	$LN22@qt_static_
	DD	$LN24@qt_static_
	DD	$LN25@qt_static_
	DD	$LN26@qt_static_
	DD	$LN27@qt_static_
	DD	$LN28@qt_static_
	DD	$LN29@qt_static_
	DD	$LN30@qt_static_
	DD	$LN31@qt_static_
?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TextEdit::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@TextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; TextEdit::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 218
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 219
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 220
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 221
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 222
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 223
	cmp	DWORD PTR _id$[rsp], 24
	jge	SHORT $LN5@qt_metacal
; Line 224
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@TextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TextEdit::qt_static_metacall
$LN5@qt_metacal:
; Line 225
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 24
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 226
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 227
	cmp	DWORD PTR _id$[rsp], 24
	jge	SHORT $LN7@qt_metacal
; Line 228
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 229
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 24
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 231
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 232
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@TextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TextEdit::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@TextEdit@@UEAAPEAXPEBD@Z PROC		; TextEdit::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 210
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 211
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 212
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_TextEdit@@3Uqt_meta_stringdata_TextEdit_t@@B+888
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 213
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 214
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 215
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@TextEdit@@UEAAPEAXPEBD@Z ENDP		; TextEdit::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@TextEdit@@UEBAPEBUQMetaObject@@XZ PROC	; TextEdit::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 205
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 206
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@TextEdit@@2UQMetaObject@@B ; TextEdit::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 207
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@TextEdit@@UEBAPEBUQMetaObject@@XZ ENDP	; TextEdit::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.12.3\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 235
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_textedit.cpp
; Line 235
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
