; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_MainWindow
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000120H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000113H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000103H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000ecH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000d9H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	00000000000000c6H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000000b5H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000000a3H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	000000000000009fH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000092H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000008bH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	000000000000007dH
	DB	04dH
	DB	061H
	DB	069H
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06eH
	DB	065H
	DB	077H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	00H
	DB	00H
	DB	06fH
	DB	070H
	DB	065H
	DB	06eH
	DB	00H
	DB	073H
	DB	061H
	DB	076H
	DB	065H
	DB	00H
	DB	073H
	DB	061H
	DB	076H
	DB	065H
	DB	041H
	DB	073H
	DB	00H
	DB	061H
	DB	062H
	DB	06fH
	DB	075H
	DB	074H
	DB	00H
	DB	064H
	DB	06fH
	DB	063H
	DB	075H
	DB	06dH
	DB	065H
	DB	06eH
	DB	074H
	DB	057H
	DB	061H
	DB	073H
	DB	04dH
	DB	06fH
	DB	064H
	DB	069H
	DB	066H
	DB	069H
	DB	065H
	DB	064H
	DB	00H
	DB	063H
	DB	06fH
	DB	06dH
	DB	06dH
	DB	069H
	DB	074H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	DB	051H
	DB	053H
	DB	065H
	DB	073H
	DB	073H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04dH
	DB	061H
	DB	06eH
	DB	061H
	DB	067H
	DB	065H
	DB	072H
	DB	026H
	DB	00H
	DB	06cH
	DB	06fH
	DB	067H
	DB	069H
	DB	06eH
	DB	050H
	DB	061H
	DB	067H
	DB	065H
	DB	00H
	DB	065H
	DB	061H
	DB	073H
	DB	079H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	045H
	DB	078H
	DB	070H
	DB	06cH
	DB	06fH
	DB	072H
	DB	065H
	DB	072H
	DB	050H
	DB	061H
	DB	067H
	DB	065H
	DB	00H
	ORG $+6
?qt_meta_data_MainWindow@@3QBIB DD 08H			; qt_meta_data_MainWindow
	DD	00H
	DD	00H
	DD	00H
	DD	09H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	03bH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	03cH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	03dH
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	03eH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	03fH
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	040H
	DD	02H
	DD	08H
	DD	08H
	DD	01H
	DD	041H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	044H
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	045H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	01H
	DD	01H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	080000009H
	DD	02H
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG121292 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG121293 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG121294 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG121653 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG121654 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG121655 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG122014 DB	'D:\QT\5.12.3\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG122015 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG122016 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ	; MainWindow::metaObject
PUBLIC	?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z		; MainWindow::qt_metacast
PUBLIC	?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_metacall
PUBLIC	?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
PUBLIC	??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z		; std::move<bool &>
PUBLIC	?staticMetaObject@MainWindow@@2UQMetaObject@@B	; MainWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?newFile@MainWindow@@AEAAXXZ:PROC		; MainWindow::newFile
EXTRN	?open@MainWindow@@AEAAXXZ:PROC			; MainWindow::open
EXTRN	?save@MainWindow@@AEAA_NXZ:PROC			; MainWindow::save
EXTRN	?saveAs@MainWindow@@AEAA_NXZ:PROC		; MainWindow::saveAs
EXTRN	?about@MainWindow@@AEAAXXZ:PROC			; MainWindow::about
EXTRN	?documentWasModified@MainWindow@@AEAAXXZ:PROC	; MainWindow::documentWasModified
EXTRN	?commitData@MainWindow@@AEAAXAEAVQSessionManager@@@Z:PROC ; MainWindow::commitData
EXTRN	?loginPage@MainWindow@@AEAAXXZ:PROC		; MainWindow::loginPage
EXTRN	?easyFileExplorerPage@MainWindow@@AEAAXXZ:PROC	; MainWindow::easyFileExplorerPage
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@MainWindow@@2UQMetaObject@@B DB 030H DUP (?) ; MainWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN19
	DD	imagerel $LN19+380
	DD	imagerel $unwind$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@MainWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@MainWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'MainWindow::staticMetaObject'', COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 116
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B, rax
; Line 117
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+8, rax
; Line 118
	lea	rax, OFFSET FLAT:?qt_meta_data_MainWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+16, rax
; Line 119
	lea	rax, OFFSET FLAT:?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+24, rax
; Line 120
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+32, 0
; Line 121
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'MainWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z
_TEXT	SEGMENT
_Arg$ = 8
??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z PROC		; std::move<bool &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\type_traits
; Line 1313
	mov	QWORD PTR [rsp+8], rcx
; Line 1314
	mov	rax, QWORD PTR _Arg$[rsp]
; Line 1315
	ret	0
??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z ENDP		; std::move<bool &>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_r$1 = 32
_r$2 = 33
tv69 = 36
_t$3 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; MainWindow::qt_static_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 94
$LN19:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 95
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 96
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$3[rsp], rax
; Line 98
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 8
	ja	$LN16@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN18@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 99
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?newFile@MainWindow@@AEAAXXZ		; MainWindow::newFile
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 100
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?open@MainWindow@@AEAAXXZ		; MainWindow::open
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 101
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?save@MainWindow@@AEAA_NXZ		; MainWindow::save
	mov	BYTE PTR _r$1[rsp], al
; Line 102
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN8@qt_static_
	lea	rcx, QWORD PTR _r$1[rsp]
	call	??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z	; std::move<bool &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR [rcx], al
$LN8@qt_static_:
	jmp	$LN2@qt_static_
$LN9@qt_static_:
; Line 103
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?saveAs@MainWindow@@AEAA_NXZ		; MainWindow::saveAs
	mov	BYTE PTR _r$2[rsp], al
; Line 104
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN10@qt_static_
	lea	rcx, QWORD PTR _r$2[rsp]
	call	??$move@AEA_N@std@@YA$$QEA_NAEA_N@Z	; std::move<bool &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR [rcx], al
$LN10@qt_static_:
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 105
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?about@MainWindow@@AEAAXXZ		; MainWindow::about
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 106
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?documentWasModified@MainWindow@@AEAAXXZ ; MainWindow::documentWasModified
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 107
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?commitData@MainWindow@@AEAAXAEAVQSessionManager@@@Z ; MainWindow::commitData
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 108
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?loginPage@MainWindow@@AEAAXXZ		; MainWindow::loginPage
	jmp	SHORT $LN2@qt_static_
$LN15@qt_static_:
; Line 109
	mov	rcx, QWORD PTR _t$3[rsp]
	call	?easyFileExplorerPage@MainWindow@@AEAAXXZ ; MainWindow::easyFileExplorerPage
$LN16@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 113
	add	rsp, 56					; 00000038H
	ret	0
	npad	3
$LN18@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN9@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; MainWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; MainWindow::qt_metacall
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 139
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 140
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 141
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 142
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 143
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 144
	cmp	DWORD PTR _id$[rsp], 9
	jge	SHORT $LN5@qt_metacal
; Line 145
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 146
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 9
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 147
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 148
	cmp	DWORD PTR _id$[rsp], 9
	jge	SHORT $LN7@qt_metacal
; Line 149
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 150
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 9
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 152
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 153
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; MainWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z PROC		; MainWindow::qt_metacast
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 131
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 132
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 133
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B+288
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 134
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 135
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 136
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z ENDP		; MainWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ PROC	; MainWindow::metaObject
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 126
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 127
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@MainWindow@@2UQMetaObject@@B ; MainWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 128
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; MainWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\QT\5.12.3\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 156
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\cgarg\source\repos\pmartellone13\PDS_Project\Client\ProgettoGUI\GeneratedFiles\Debug\moc_mainwindow.cpp
; Line 156
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
